### ISSUE TITLE
Error when searching for 'skandieren'

### ISSUE THREAD

**Issue by dbohn** [deanishe/alfred-duden#1]
When I search for 'skandieren' Alfred displays an error message:

'NoneType' object has no attribute 'strip'
<img width="594" alt="screenshot 2015-08-30 02 11 10" src="https://cloud.githubusercontent.com/assets/166164/9565112/7ffeb804-4ebc-11e5-85ff-85dd8d8df948.png">

**Comment by deanishe** [comment]
Thanks for finding that. Fixed in [version 1.2](https://github.com/deanishe/alfred-duden/releases/latest).
