### ISSUE TITLE
URL on the Alfred Results

### ISSUE THREAD

**Issue by jothirams** [deanishe/alfred-duden#2]
Hello,

For e.g. when I search "duden durchregnen"

I get two results. Both look identical. The result was - one was with the url trennbar and one untrennbar. 

If you could show the URL, when I for example, press the Shift or Options key on the results, then it will be helpful in such cases.

**Comment by deanishe** [comment]
Yeah, they do look almost the same. The same is true when you search on the Duden.de website, though.

Still, you make a good point: it would be useful to be able see the URL in such cases. Perhaps it'd be even better to add the separable/inseparable info to the displayed result. I'll do the first and look into the second.

Fun German fact: when you have a separable and an inseparable verb that are written the same, the separable verb has the stress on the second syllable, e.g. **um**fahren (inseparable/drive around sth.) and um**fah**ren (separable/run sth. down).

**Comment by deanishe** [comment]
Forgot to mention this is fixed in [v1.3](https://github.com/deanishe/alfred-duden/releases/tag/v1.3).
